spring.application.name=jobportal
logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:jobportal}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}

spring.sql.init.schema-locations=classpath:sql/jobportal-schema.sql
spring.sql.init.data-locations=classpath:sql/jobportal-data.sql
#spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.start.command=up
spring.docker.compose.stop.command=stop
